{
    "name": "Factura Electrónica CR Hacienda Connector",
    "summary": "Integra Odoo 19 con Hacienda Costa Rica (Recepción v4.4)",
    "version": "19.0.5.0.4",
    "category": "Accounting",
    "license": "LGPL-3",
    "depends": ["account", "product", "uom"],
    "data": [
        "security/ir.model.access.csv",
        "data/fp_cabys_code_data.xml",
        "views/res_config_settings_views.xml",
        "views/res_partner_views.xml",
        "views/account_move_views.xml",
        "views/fp_electronic_document_views.xml",
        "views/account_tax_views.xml",
        "views/account_journal_views.xml",
        "views/account_invoice_report_views.xml",
        "views/product_template_views.xml",
        "views/uom_uom_views.xml",
        "views/fp_catalog_views.xml",
        "data/ir_cron_data.xml",
    ],
    "installable": True,
    "application": True,
}
